### ISSUE TITLE
MBoxReader' object has no attribute 'filter_by_date'

### ISSUE THREAD

**Issue by kwidyas** [onlyphantom/emailnetwork#11]
I got this error. How this can be solved? Thank you

AttributeError                            Traceback (most recent call last)
Input In [3], in <module>
      9 emailmsg = extract_meta(email)
     11 # filter emails by certain date
---> 12 thisyearmails = reader.filter_by_date('>=', '2021-01-05')
     14 # print email domains of recipients
     15 print(emailmsg.recipients)

AttributeError: 'MBoxReader' object has no attribute 'filter_by_date'

**Comment by staneaurelius** [comment]
The `filter_by_date` method was modified into `filter_emails`. Use these instead for filtering emails:
```
thisyearmails = reader.filter_emails(dateoperator = '>=', datestring = '2021-01-05')
```

**Comment by kwidyas** [comment]
Thank you Stane!
